"""Pilot acceptance load profile.

Design doc §11: 50 requests/s sustained, 200 requests/s for a bounded
five-minute burst, with a realistic mix of search, CRUD and uploads.

    # sustained
    uv run --project ../../apps/api locust -f locustfile.py \
        --host http://localhost:3000 --users 200 --spawn-rate 10 \
        --run-time 10m --headless

    # burst
    uv run --project ../../apps/api locust -f locustfile.py \
        --host http://localhost:3000 --users 800 --spawn-rate 100 \
        --run-time 5m --headless

Results from a laptop are not capacity. They exercise the paths and surface
correctness failures under concurrency; the numbers that matter come from the
declared production hardware.
"""

from __future__ import annotations

import io
import random

from locust import HttpUser, between, events, tag, task

PASSWORD = "moat-dev-password"

# A workspace full of researchers is the wrong shape. Real load is mostly
# reading, with a much smaller amount of writing and a little heavy work.
ACCOUNTS = [
    ("priya@northwind.example", 4),
    ("daniel@northwind.example", 4),
    ("hana@northwind.example", 3),
    ("mei@northwind.example", 2),
    ("viktor@northwind.example", 2),
    ("ines@vantage.example", 2),
    ("omar@vantage.example", 1),
]

SEARCH_PHRASES = [
    "joint stiffness control from winding temperature",
    "robot arm compliance near an operator",
    "battery cell balancing by predicted temperature",
    "stereo baseline self calibration during operation",
    "optical beam steering without moving parts",
    "attention head eviction under memory pressure",
]

_WEIGHTED = [email for email, weight in ACCOUNTS for _ in range(weight)]


@events.test_start.add_listener
def on_start(environment, **_kwargs):
    print("\nLoad profile: read-heavy with periodic writes and occasional uploads.")
    print("Watch moat_admission_rejections_total: 429s here are the system")
    print("working, not failing. 503s are not.\n")


class Researcher(HttpUser):
    """One signed-in browser session."""

    # Think time. Hammering with zero delay measures the load generator, not
    # the product.
    wait_time = between(1, 5)

    def on_start(self) -> None:
        self.email = random.choice(_WEIGHTED)
        self.invention_ids: list[str] = []

        with self.client.post(
            "/api/v1/auth/login",
            json={"email": self.email, "password": PASSWORD},
            headers={"origin": self.host},
            name="POST /auth/login",
            catch_response=True,
        ) as response:
            if response.status_code != 200:
                response.failure(f"login failed: {response.status_code}")
                self.environment.runner.quit()
                return

        self._refresh_inventions()

    def _refresh_inventions(self) -> None:
        with self.client.get(
            "/api/v1/inventions", name="GET /inventions", catch_response=True
        ) as response:
            if response.status_code == 200:
                self.invention_ids = [row["id"] for row in response.json()]

    @tag("read")
    @task(12)
    def list_inventions(self) -> None:
        self.client.get("/api/v1/inventions", name="GET /inventions")

    @tag("read")
    @task(10)
    def read_invention(self) -> None:
        if not self.invention_ids:
            return self._refresh_inventions()
        target = random.choice(self.invention_ids)
        self.client.get(f"/api/v1/inventions/{target}", name="GET /inventions/{id}")

    @tag("read")
    @task(4)
    def read_documents(self) -> None:
        if not self.invention_ids:
            return
        target = random.choice(self.invention_ids)
        self.client.get(
            f"/api/v1/inventions/{target}/documents", name="GET /inventions/{id}/documents"
        )

    @tag("read")
    @task(4)
    def notifications(self) -> None:
        self.client.get("/api/v1/notifications", name="GET /notifications")

    @tag("read")
    @task(2)
    def colleagues(self) -> None:
        self.client.get("/api/v1/users", name="GET /users")

    @tag("write")
    @task(2)
    def create_disclosure(self) -> None:
        phrase = random.choice(SEARCH_PHRASES)
        with self.client.post(
            "/api/v1/inventions",
            json={
                "title": f"Load test: {phrase}"[:200],
                "summary": phrase,
                "problem": "Generated by the load profile.",
                "description": f"{phrase}. " * 20,
                "classifications": ["B25J 9/16"],
            },
            headers={"origin": self.host},
            name="POST /inventions",
            catch_response=True,
        ) as response:
            if response.status_code == 201:
                self.invention_ids.append(response.json()["id"])
            elif response.status_code == 403:
                # Roles without invention.create are expected to be refused.
                response.success()

    @tag("write")
    @task(2)
    def edit_disclosure(self) -> None:
        if not self.invention_ids:
            return
        target = random.choice(self.invention_ids)
        current = self.client.get(
            f"/api/v1/inventions/{target}", name="GET /inventions/{id}"
        )
        if current.status_code != 200:
            return
        body = current.json()
        with self.client.put(
            f"/api/v1/inventions/{target}",
            json={
                "title": body["title"],
                "summary": body["summary"],
                "problem": body["problem"],
                "description": body["description"],
                "classifications": body["classifications"],
                "baseRevision": body["revision"],
            },
            headers={"origin": self.host},
            name="PUT /inventions/{id}",
            catch_response=True,
        ) as response:
            # A 409 under concurrency is the optimistic-concurrency check
            # working. Counting it as an error would hide real failures.
            if response.status_code in (403, 409):
                response.success()

    @tag("search")
    @task(3)
    def run_analysis(self) -> None:
        """The expensive path. Admission control should shed these first."""
        if not self.invention_ids:
            return
        target = random.choice(self.invention_ids)
        with self.client.post(
            f"/api/v1/inventions/{target}/analyses",
            headers={"origin": self.host},
            name="POST /inventions/{id}/analyses",
            catch_response=True,
        ) as response:
            if response.status_code in (202, 403):
                response.success()
            elif response.status_code == 429:
                # The tenant cap refusing work is correct behaviour under load.
                response.success()

    @tag("upload")
    @task(1)
    def upload_document(self) -> None:
        if not self.invention_ids:
            return
        target = random.choice(self.invention_ids)
        payload = io.BytesIO(
            (f"{random.choice(SEARCH_PHRASES)}\n" * 200).encode("utf-8")
        ).getvalue()

        with self.client.post(
            "/api/v1/uploads",
            json={
                "filename": f"load-{random.randint(1, 10**9)}.txt",
                "contentType": "text/plain",
                "size": len(payload),
                "inventionId": target,
            },
            headers={"origin": self.host},
            name="POST /uploads",
            catch_response=True,
        ) as response:
            if response.status_code == 429:
                response.success()
                return
            if response.status_code != 201:
                if response.status_code == 403:
                    response.success()
                return
            reserved = response.json()

        self.client.post(
            reserved["uploadUrl"],
            files={"file": ("load.txt", payload, "text/plain")},
            headers={"origin": self.host},
            name="POST /uploads/{id}/content",
        )
        with self.client.post(
            f"/api/v1/uploads/{reserved['uploadId']}/complete",
            json={},
            headers={"origin": self.host},
            name="POST /uploads/{id}/complete",
            catch_response=True,
        ) as response:
            if response.status_code in (202, 429):
                response.success()
