"use client";

import { BellRing, ShieldAlert, Users, Zap, CheckCircle2 } from "lucide-react";

export default function EmailAlertsPage() {
  const alertCategories = [
    {
      title: "Security & Access",
      icon: ShieldAlert,
      items: [
        { name: "Multiple Failed Login Attempts", description: "Triggered after 5 consecutive failures.", active: true },
        { name: "New Device Login", description: "When a user logs in from an unrecognized device/IP.", active: false },
        { name: "Permission Drift Detected", description: "When AI Insight detects abnormal role escalation.", active: true }
      ]
    },
    {
      title: "User Management",
      icon: Users,
      items: [
        { name: "New User Provisioned", description: "Sent to admins when a new enterprise user is created.", active: true },
        { name: "Password Reset Requested", description: "Sent to the user when a reset is initiated.", active: true },
        { name: "Account Locked", description: "Sent to admins when an account is automatically locked.", active: true }
      ]
    },
    {
      title: "System & AI Insights",
      icon: Zap,
      items: [
        { name: "High Severity AI Alert", description: "Critical insights generated by the AI engine.", active: true },
        { name: "Weekly Executive Digest", description: "Automated rollup of system metrics and alerts.", active: false },
        { name: "System Outage / Error", description: "Immediate notification on API or Database failure.", active: true }
      ]
    }
  ];

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-xl font-bold text-foreground">Email Alerts & Notifications</h2>
          <p className="text-sm text-muted-foreground">Manage which events trigger automated email notifications.</p>
        </div>
        <button className="bg-[#c9a84c] hover:bg-[#b8921e] text-white px-6 py-2 rounded-xl text-sm font-bold transition-all shadow-md shadow-[#c9a84c]/20">
          Save Preferences
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 space-y-6">
          {alertCategories.map((category) => (
            <div key={category.title} className="rounded-2xl border border-border bg-card overflow-hidden shadow-sm">
              <div className="p-5 border-b border-border/50 bg-muted/10">
                <div className="flex items-center gap-2">
                  <category.icon className="h-5 w-5 text-[#c9a84c]" />
                  <h3 className="font-bold text-foreground">{category.title}</h3>
                </div>
              </div>
              <div className="divide-y divide-border/50">
                {category.items.map((item) => (
                  <div key={item.name} className="p-5 flex items-center justify-between hover:bg-muted/10 transition-colors">
                    <div>
                      <h4 className="font-medium text-foreground text-sm">{item.name}</h4>
                      <p className="text-xs text-muted-foreground mt-1">{item.description}</p>
                    </div>
                    <label className="relative inline-flex items-center cursor-pointer">
                      <input type="checkbox" className="sr-only peer" defaultChecked={item.active} />
                      <div className="w-11 h-6 bg-muted peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-[#c9a84c]"></div>
                    </label>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>

        <div className="space-y-6">
          <div className="rounded-2xl border border-border bg-card overflow-hidden shadow-sm">
            <div className="p-5 border-b border-border/50 bg-muted/10">
              <div className="flex items-center gap-2">
                <BellRing className="h-5 w-5 text-[#c9a84c]" />
                <h3 className="font-bold text-foreground">Global Settings</h3>
              </div>
            </div>
            <div className="p-5 space-y-4">
              <div className="flex items-center gap-3 p-3 bg-emerald-500/10 border border-emerald-500/20 rounded-xl text-emerald-600 dark:text-emerald-400">
                <CheckCircle2 className="h-5 w-5 shrink-0" />
                <p className="text-xs font-medium">SMTP Email Server is correctly configured and active.</p>
              </div>
              
              <div className="space-y-2 pt-2">
                <label className="text-sm font-medium text-muted-foreground">Daily Digest Time (UTC)</label>
                <select className="w-full bg-background border border-border rounded-lg px-4 py-2.5 text-sm text-foreground focus:outline-none focus:border-[#c9a84c]/50">
                  <option>00:00</option>
                  <option>06:00</option>
                  <option>12:00</option>
                  <option>18:00</option>
                </select>
              </div>
              
              <div className="space-y-2">
                <label className="text-sm font-medium text-muted-foreground">Admin Alert Recipient</label>
                <input 
                  type="email" 
                  defaultValue="security@moatplatform.io" 
                  className="w-full bg-background border border-border rounded-lg px-4 py-2.5 text-sm text-foreground focus:outline-none focus:border-[#c9a84c]/50"
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
