"""drafting: documents, claim sets, claims

Revision ID: 0b64c6587118
Revises: 0005_policies_execution
Create Date: 2026-09-11 12:26:43.482026
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0b64c6587118'
down_revision: str | None = '0005_policies_execution'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('invention_id', sa.UUID(), nullable=False),
    sa.Column('ref', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='drafting', nullable=False),
    sa.Column('current_revision', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('drafter_id', sa.UUID(), nullable=True),
    sa.Column('jurisdiction', sa.String(length=8), server_default='US', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['drafter_id'], ['users.id'], name=op.f('fk_documents_drafter_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id', 'invention_id'], ['inventions.tenant_id', 'inventions.id'], name='fk_documents_invention', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_documents_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_documents_tenant_id_id'),
    sa.UniqueConstraint('tenant_id', 'ref', name='uq_documents_tenant_ref')
    )
    op.create_index(op.f('ix_documents_tenant_id'), 'documents', ['tenant_id'], unique=False)
    op.create_index('ix_documents_tenant_status', 'documents', ['tenant_id', 'status', 'updated_at', 'id'], unique=False)
    op.create_table('claim_sets',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('change_note', sa.String(length=300), server_default='', nullable=False),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_claim_sets_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id', 'document_id'], ['documents.tenant_id', 'documents.id'], name='fk_claim_sets_document', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_claim_sets_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim_sets')),
    sa.UniqueConstraint('tenant_id', 'document_id', 'revision', name='uq_claim_sets_revision'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_claim_sets_tenant_id_id')
    )
    op.create_index('ix_claim_sets_document', 'claim_sets', ['tenant_id', 'document_id', 'revision'], unique=False)
    op.create_index(op.f('ix_claim_sets_tenant_id'), 'claim_sets', ['tenant_id'], unique=False)
    op.create_table('document_versions',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('abstract', sa.Text(), server_default='', nullable=False),
    sa.Column('technical_field', sa.Text(), server_default='', nullable=False),
    sa.Column('background', sa.Text(), server_default='', nullable=False),
    sa.Column('summary', sa.Text(), server_default='', nullable=False),
    sa.Column('brief_description_of_drawings', sa.Text(), server_default='', nullable=False),
    sa.Column('detailed_description', sa.Text(), server_default='', nullable=False),
    sa.Column('authored_by_id', sa.UUID(), nullable=True),
    sa.Column('change_note', sa.String(length=300), server_default='', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['authored_by_id'], ['users.id'], name=op.f('fk_document_versions_authored_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id', 'document_id'], ['documents.tenant_id', 'documents.id'], name='fk_document_versions_document', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_document_versions_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_versions')),
    sa.UniqueConstraint('tenant_id', 'document_id', 'revision', name='uq_document_versions_revision')
    )
    op.create_index(op.f('ix_document_versions_tenant_id'), 'document_versions', ['tenant_id'], unique=False)
    op.create_table('claims',
    sa.Column('claim_set_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), server_default='independent', nullable=False),
    sa.Column('category', sa.String(length=16), server_default='other', nullable=False),
    sa.Column('preamble', sa.Text(), server_default='', nullable=False),
    sa.Column('transition', sa.String(length=64), server_default='comprising', nullable=False),
    sa.Column('body', sa.Text(), server_default='', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'claim_set_id'], ['claim_sets.tenant_id', 'claim_sets.id'], name='fk_claims_claim_set', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_claims_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims')),
    sa.UniqueConstraint('tenant_id', 'claim_set_id', 'number', name='uq_claims_number'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_claims_tenant_id_id')
    )
    op.create_index('ix_claims_set_number', 'claims', ['tenant_id', 'claim_set_id', 'number'], unique=False)
    op.create_index(op.f('ix_claims_tenant_id'), 'claims', ['tenant_id'], unique=False)
    op.create_table('claim_dependencies',
    sa.Column('claim_set_id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('parent_claim_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'claim_id'], ['claims.tenant_id', 'claims.id'], name='fk_claim_dependencies_claim', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'claim_set_id'], ['claim_sets.tenant_id', 'claim_sets.id'], name='fk_claim_dependencies_set', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'parent_claim_id'], ['claims.tenant_id', 'claims.id'], name='fk_claim_dependencies_parent', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_claim_dependencies_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim_dependencies')),
    sa.UniqueConstraint('tenant_id', 'claim_id', 'parent_claim_id', name='uq_claim_dependencies_edge')
    )
    op.create_index('ix_claim_dependencies_set', 'claim_dependencies', ['tenant_id', 'claim_set_id'], unique=False)
    op.create_index(op.f('ix_claim_dependencies_tenant_id'), 'claim_dependencies', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claim_dependencies_tenant_id'), table_name='claim_dependencies')
    op.drop_index('ix_claim_dependencies_set', table_name='claim_dependencies')
    op.drop_table('claim_dependencies')
    op.drop_index(op.f('ix_claims_tenant_id'), table_name='claims')
    op.drop_index('ix_claims_set_number', table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_document_versions_tenant_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_claim_sets_tenant_id'), table_name='claim_sets')
    op.drop_index('ix_claim_sets_document', table_name='claim_sets')
    op.drop_table('claim_sets')
    op.drop_index('ix_documents_tenant_status', table_name='documents')
    op.drop_index(op.f('ix_documents_tenant_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
