"""initial schema

Revision ID: 1b7250160424
Revises: 
Create Date: 2026-09-11 10:16:16.108453
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1b7250160424'
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('key', sa.String(length=96), nullable=False),
    sa.Column('description', sa.String(length=300), server_default='', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('key', name=op.f('uq_permissions_key'))
    )
    op.create_table('roles',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), server_default='', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('key', name=op.f('uq_roles_key'))
    )
    op.create_table('tenants',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('slug', name=op.f('uq_tenants_slug'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('external_subject', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('external_subject', name=op.f('uq_users_external_subject'))
    )
    op.create_table('app_sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('membership_revision', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=400), server_default='', nullable=False),
    sa.Column('client_ip', sa.String(length=64), server_default='', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_app_sessions_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_app_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_app_sessions_token_hash'))
    )
    op.create_index('ix_app_sessions_user_expiry', 'app_sessions', ['user_id', 'expires_at'], unique=False)
    op.create_table('audit_events',
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=96), nullable=False),
    sa.Column('resource_type', sa.String(length=48), server_default='', nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('request_id', sa.String(length=64), server_default='', nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_events_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_audit_events_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index('ix_audit_events_resource', 'audit_events', ['tenant_id', 'resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_index('ix_audit_events_tenant_time', 'audit_events', ['tenant_id', 'created_at'], unique=False)
    op.create_table('comments',
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('anchor_revision', sa.Integer(), nullable=True),
    sa.Column('anchor_text', sa.Text(), server_default='', nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_comments_author_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], name=op.f('fk_comments_parent_id_comments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_comments_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    op.create_index('ix_comments_target', 'comments', ['tenant_id', 'target_type', 'target_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_comments_tenant_id'), 'comments', ['tenant_id'], unique=False)
    op.create_table('inventions',
    sa.Column('ref', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), server_default='', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='draft', nullable=False),
    sa.Column('current_revision', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('classifications', postgresql.ARRAY(sa.String(length=32)), server_default=sa.text("'{}'::varchar[]"), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_inventions_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_inventions_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventions')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_inventions_tenant_id_id'),
    sa.UniqueConstraint('tenant_id', 'ref', name='uq_inventions_tenant_ref')
    )
    op.create_index(op.f('ix_inventions_tenant_id'), 'inventions', ['tenant_id'], unique=False)
    op.create_index('ix_inventions_tenant_status_updated', 'inventions', ['tenant_id', 'status', 'updated_at', 'id'], unique=False)
    op.create_table('memberships',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('revision', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_memberships_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_memberships_tenant_id_id'),
    sa.UniqueConstraint('tenant_id', 'user_id', name='uq_memberships_tenant_user')
    )
    op.create_index('ix_memberships_user_active', 'memberships', ['user_id', 'is_active'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), server_default='', nullable=False),
    sa.Column('target_type', sa.String(length=32), server_default='', nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('action_url', sa.String(length=500), server_default='', nullable=False),
    sa.Column('priority', sa.String(length=16), server_default='medium', nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_notifications_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_recipient', 'notifications', ['tenant_id', 'user_id', 'read_at', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('analysis_runs',
    sa.Column('invention_id', sa.UUID(), nullable=False),
    sa.Column('invention_revision', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='queued', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('corpus_revision', sa.String(length=64), nullable=False),
    sa.Column('retrieval_version', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('failure_category', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'invention_id'], ['inventions.tenant_id', 'inventions.id'], name='fk_analysis_runs_invention', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_analysis_runs_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_runs')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_analysis_runs_tenant_id_id')
    )
    op.create_index('ix_analysis_runs_invention_started', 'analysis_runs', ['tenant_id', 'invention_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_analysis_runs_tenant_id'), 'analysis_runs', ['tenant_id'], unique=False)
    op.create_table('invention_contributors',
    sa.Column('invention_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('contribution', sa.String(length=200), server_default='', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'invention_id'], ['inventions.tenant_id', 'inventions.id'], name='fk_invention_contributors_invention', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_invention_contributors_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_invention_contributors_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invention_contributors')),
    sa.UniqueConstraint('tenant_id', 'invention_id', 'user_id', name='uq_invention_contributors_unique')
    )
    op.create_index(op.f('ix_invention_contributors_tenant_id'), 'invention_contributors', ['tenant_id'], unique=False)
    op.create_table('invention_versions',
    sa.Column('invention_id', sa.UUID(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), server_default='', nullable=False),
    sa.Column('problem', sa.Text(), server_default='', nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('classifications', postgresql.ARRAY(sa.String(length=32)), server_default=sa.text("'{}'::varchar[]"), nullable=False),
    sa.Column('authored_by_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['authored_by_id'], ['users.id'], name=op.f('fk_invention_versions_authored_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'invention_id'], ['inventions.tenant_id', 'inventions.id'], name='fk_invention_versions_invention', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_invention_versions_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invention_versions')),
    sa.UniqueConstraint('tenant_id', 'invention_id', 'revision', name='uq_invention_versions_revision')
    )
    op.create_index(op.f('ix_invention_versions_tenant_id'), 'invention_versions', ['tenant_id'], unique=False)
    op.create_table('membership_roles',
    sa.Column('membership_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], name=op.f('fk_membership_roles_membership_id_memberships'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_membership_roles_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('membership_id', 'role_id', name=op.f('pk_membership_roles'))
    )
    op.create_table('submissions',
    sa.Column('invention_id', sa.UUID(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=32), server_default='open', nullable=False),
    sa.Column('submitted_by_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), server_default='', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_submissions_assigned_to_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], name=op.f('fk_submissions_submitted_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'invention_id'], ['inventions.tenant_id', 'inventions.id'], name='fk_submissions_invention', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_submissions_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_submissions')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_submissions_tenant_id_id'),
    sa.UniqueConstraint('tenant_id', 'invention_id', 'revision', name='uq_submissions_invention_revision')
    )
    op.create_index(op.f('ix_submissions_tenant_id'), 'submissions', ['tenant_id'], unique=False)
    op.create_index('ix_submissions_tenant_state', 'submissions', ['tenant_id', 'state', 'created_at'], unique=False)
    op.create_table('analysis_concepts',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('matches', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'run_id'], ['analysis_runs.tenant_id', 'analysis_runs.id'], name='fk_analysis_concepts_run', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_analysis_concepts_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_concepts'))
    )
    op.create_index(op.f('ix_analysis_concepts_tenant_id'), 'analysis_concepts', ['tenant_id'], unique=False)
    op.create_table('decisions',
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('invention_id', sa.UUID(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_decisions_reviewer_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'invention_id'], ['inventions.tenant_id', 'inventions.id'], name='fk_decisions_invention', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'submission_id'], ['submissions.tenant_id', 'submissions.id'], name='fk_decisions_submission', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_decisions_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions'))
    )
    op.create_index('ix_decisions_invention', 'decisions', ['tenant_id', 'invention_id', 'decided_at'], unique=False)
    op.create_index(op.f('ix_decisions_tenant_id'), 'decisions', ['tenant_id'], unique=False)
    op.create_table('evidence_links',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('publication_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('applicant', sa.String(length=300), server_default='', nullable=False),
    sa.Column('jurisdiction', sa.String(length=8), nullable=False),
    sa.Column('kind_code', sa.String(length=8), server_default='', nullable=False),
    sa.Column('published_on', sa.Date(), nullable=True),
    sa.Column('passage', sa.Text(), nullable=False),
    sa.Column('retrieval_score', sa.Float(), nullable=False),
    sa.Column('matched_concepts', postgresql.ARRAY(sa.String(length=300)), server_default=sa.text("'{}'::varchar[]"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'run_id'], ['analysis_runs.tenant_id', 'analysis_runs.id'], name='fk_evidence_links_run', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_evidence_links_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_links'))
    )
    op.create_index('ix_evidence_links_run_score', 'evidence_links', ['tenant_id', 'run_id', 'retrieval_score'], unique=False)
    op.create_index(op.f('ix_evidence_links_tenant_id'), 'evidence_links', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_links_tenant_id'), table_name='evidence_links')
    op.drop_index('ix_evidence_links_run_score', table_name='evidence_links')
    op.drop_table('evidence_links')
    op.drop_index(op.f('ix_decisions_tenant_id'), table_name='decisions')
    op.drop_index('ix_decisions_invention', table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_analysis_concepts_tenant_id'), table_name='analysis_concepts')
    op.drop_table('analysis_concepts')
    op.drop_index('ix_submissions_tenant_state', table_name='submissions')
    op.drop_index(op.f('ix_submissions_tenant_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_table('membership_roles')
    op.drop_index(op.f('ix_invention_versions_tenant_id'), table_name='invention_versions')
    op.drop_table('invention_versions')
    op.drop_index(op.f('ix_invention_contributors_tenant_id'), table_name='invention_contributors')
    op.drop_table('invention_contributors')
    op.drop_index(op.f('ix_analysis_runs_tenant_id'), table_name='analysis_runs')
    op.drop_index('ix_analysis_runs_invention_started', table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_index('ix_notifications_recipient', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_memberships_user_active', table_name='memberships')
    op.drop_table('memberships')
    op.drop_index('ix_inventions_tenant_status_updated', table_name='inventions')
    op.drop_index(op.f('ix_inventions_tenant_id'), table_name='inventions')
    op.drop_table('inventions')
    op.drop_index(op.f('ix_comments_tenant_id'), table_name='comments')
    op.drop_index('ix_comments_target', table_name='comments')
    op.drop_table('comments')
    op.drop_index('ix_audit_events_tenant_time', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_index('ix_audit_events_resource', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('ix_app_sessions_user_expiry', table_name='app_sessions')
    op.drop_table('app_sessions')
    op.drop_table('users')
    op.drop_table('tenants')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
