"""execution, uploads and index manifests

Revision ID: 1f6ac15a80b8
Revises: 0003_public_corpus
Create Date: 2026-09-11 10:59:39.038212
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1f6ac15a80b8'
down_revision: str | None = '0003_public_corpus'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index_manifests',
    sa.Column('index_name', sa.String(length=120), nullable=False),
    sa.Column('alias', sa.String(length=120), nullable=False),
    sa.Column('corpus_revision', sa.String(length=64), nullable=False),
    sa.Column('retrieval_version', sa.String(length=64), nullable=False),
    sa.Column('embedding_model', sa.String(length=120), server_default='', nullable=False),
    sa.Column('embedding_dimensions', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('document_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('state', sa.String(length=16), server_default='building', nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_index_manifests')),
    sa.UniqueConstraint('index_name', name='uq_index_manifests_name')
    )
    op.create_table('consumer_receipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('consumer', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_consumer_receipts_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consumer_receipts')),
    sa.UniqueConstraint('consumer', 'event_id', name='uq_consumer_receipts_event')
    )
    op.create_index(op.f('ix_consumer_receipts_tenant_id'), 'consumer_receipts', ['tenant_id'], unique=False)
    op.create_table('jobs',
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='queued', nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('requested_by_id', sa.UUID(), nullable=True),
    sa.Column('subject_type', sa.String(length=32), server_default='', nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('progress', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('detail', sa.String(length=300), server_default='', nullable=False),
    sa.Column('workflow_id', sa.String(length=200), server_default='', nullable=False),
    sa.Column('run_id', sa.String(length=200), server_default='', nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('failure_category', sa.String(length=64), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_jobs_requested_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_jobs_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_jobs_tenant_id_id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_jobs_tenant_idempotency')
    )
    op.create_index('ix_jobs_admission', 'jobs', ['tenant_id', 'kind', 'status'], unique=False)
    op.create_index('ix_jobs_listing', 'jobs', ['tenant_id', 'created_at', 'id'], unique=False)
    op.create_index(op.f('ix_jobs_tenant_id'), 'jobs', ['tenant_id'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_type', sa.String(length=32), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=True),
    sa.Column('workflow_id', sa.String(length=200), nullable=False),
    sa.Column('task_queue', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('claimed_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_by', sa.String(length=120), server_default='', nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.Text(), server_default='', nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_outbox_events_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_events'))
    )
    op.create_index(op.f('ix_outbox_events_tenant_id'), 'outbox_events', ['tenant_id'], unique=False)
    op.create_index('ix_outbox_pending', 'outbox_events', ['claimed_until', 'id'], unique=False, postgresql_where=sa.text('delivered_at IS NULL'))
    op.create_table('upload_sessions',
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('declared_size', sa.BigInteger(), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('state', sa.String(length=16), server_default='reserved', nullable=False),
    sa.Column('actual_size', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.String(length=64), server_default='', nullable=False),
    sa.Column('rejection_reason', sa.String(length=200), server_default='', nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('invention_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_upload_sessions_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_upload_sessions_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_upload_sessions')),
    sa.UniqueConstraint('object_key', name='uq_upload_sessions_object_key'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_upload_sessions_tenant_id_id')
    )
    op.create_index('ix_upload_sessions_expiry', 'upload_sessions', ['tenant_id', 'state', 'expires_at'], unique=False)
    op.create_index(op.f('ix_upload_sessions_tenant_id'), 'upload_sessions', ['tenant_id'], unique=False)
    op.create_table('failed_jobs',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('failure_category', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.Text(), server_default='', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.String(length=32), server_default='', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'job_id'], ['jobs.tenant_id', 'jobs.id'], name='fk_failed_jobs_job', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_failed_jobs_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_failed_jobs'))
    )
    op.create_index('ix_failed_jobs_open', 'failed_jobs', ['tenant_id', 'resolved_at'], unique=False)
    op.create_index(op.f('ix_failed_jobs_tenant_id'), 'failed_jobs', ['tenant_id'], unique=False)
    op.create_table('job_attempts',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=16), server_default='running', nullable=False),
    sa.Column('worker', sa.String(length=120), server_default='', nullable=False),
    sa.Column('error', sa.Text(), server_default='', nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'job_id'], ['jobs.tenant_id', 'jobs.id'], name='fk_job_attempts_job', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_job_attempts_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_attempts')),
    sa.UniqueConstraint('tenant_id', 'job_id', 'attempt', name='uq_job_attempts_number')
    )
    op.create_index(op.f('ix_job_attempts_tenant_id'), 'job_attempts', ['tenant_id'], unique=False)
    op.create_table('source_objects',
    sa.Column('invention_id', sa.UUID(), nullable=True),
    sa.Column('upload_session_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=16), server_default='quarantined', nullable=False),
    sa.Column('rejection_reason', sa.String(length=300), server_default='', nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('pages_needing_ocr', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'invention_id'], ['inventions.tenant_id', 'inventions.id'], name='fk_source_objects_invention', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_source_objects_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_source_objects_uploaded_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_objects')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_source_objects_tenant_id_id'),
    sa.UniqueConstraint('tenant_id', 'sha256', name='uq_source_objects_tenant_sha256')
    )
    op.create_index('ix_source_objects_invention', 'source_objects', ['tenant_id', 'invention_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_source_objects_tenant_id'), 'source_objects', ['tenant_id'], unique=False)
    op.create_table('extraction_artifacts',
    sa.Column('source_object_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('page_number', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('object_key', sa.String(length=500), server_default='', nullable=False),
    sa.Column('inline_text', sa.Text(), server_default='', nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('sha256', sa.String(length=64), server_default='', nullable=False),
    sa.Column('extractor', sa.String(length=64), server_default='', nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'source_object_id'], ['source_objects.tenant_id', 'source_objects.id'], name='fk_extraction_artifacts_source', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_extraction_artifacts_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extraction_artifacts')),
    sa.UniqueConstraint('tenant_id', 'source_object_id', 'kind', 'page_number', name='uq_extraction_artifacts_unique')
    )
    op.create_index(op.f('ix_extraction_artifacts_tenant_id'), 'extraction_artifacts', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_publications_jurisdiction'), table_name='publications')
    op.drop_index(op.f('ix_publications_published_on'), table_name='publications')
    op.drop_index(op.f('ix_publications_search'), table_name='publications', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_publications_search'), 'publications', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_publications_published_on'), 'publications', ['published_on'], unique=False)
    op.create_index(op.f('ix_publications_jurisdiction'), 'publications', ['jurisdiction', 'published_on'], unique=False)
    op.drop_index(op.f('ix_extraction_artifacts_tenant_id'), table_name='extraction_artifacts')
    op.drop_table('extraction_artifacts')
    op.drop_index(op.f('ix_source_objects_tenant_id'), table_name='source_objects')
    op.drop_index('ix_source_objects_invention', table_name='source_objects')
    op.drop_table('source_objects')
    op.drop_index(op.f('ix_job_attempts_tenant_id'), table_name='job_attempts')
    op.drop_table('job_attempts')
    op.drop_index(op.f('ix_failed_jobs_tenant_id'), table_name='failed_jobs')
    op.drop_index('ix_failed_jobs_open', table_name='failed_jobs')
    op.drop_table('failed_jobs')
    op.drop_index(op.f('ix_upload_sessions_tenant_id'), table_name='upload_sessions')
    op.drop_index('ix_upload_sessions_expiry', table_name='upload_sessions')
    op.drop_table('upload_sessions')
    op.drop_index('ix_outbox_pending', table_name='outbox_events', postgresql_where=sa.text('delivered_at IS NULL'))
    op.drop_index(op.f('ix_outbox_events_tenant_id'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_jobs_tenant_id'), table_name='jobs')
    op.drop_index('ix_jobs_listing', table_name='jobs')
    op.drop_index('ix_jobs_admission', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_consumer_receipts_tenant_id'), table_name='consumer_receipts')
    op.drop_table('consumer_receipts')
    op.drop_table('index_manifests')
    # ### end Alembic commands ###
