"""drawings for the design team

Revision ID: b49840ab2569
Revises: 0009_policies_claim_decisions
Create Date: 2026-09-11 16:44:00.819310
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b49840ab2569'
down_revision: str | None = '0009_policies_claim_decisions'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drawings',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('figure_number', sa.Integer(), nullable=False),
    sa.Column('caption', sa.String(length=500), server_default='', nullable=False),
    sa.Column('brief', sa.Text(), server_default='', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='requested', nullable=False),
    sa.Column('current_version', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('requested_by_id', sa.UUID(), nullable=True),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_drawings_assigned_to_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_drawings_requested_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id', 'document_id'], ['documents.tenant_id', 'documents.id'], name='fk_drawings_document', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_drawings_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drawings')),
    sa.UniqueConstraint('tenant_id', 'document_id', 'figure_number', name='uq_drawings_figure'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_drawings_tenant_id_id')
    )
    op.create_index('ix_drawings_assignee', 'drawings', ['tenant_id', 'assigned_to_id', 'status'], unique=False)
    op.create_index('ix_drawings_queue', 'drawings', ['tenant_id', 'status', 'updated_at'], unique=False)
    op.create_index(op.f('ix_drawings_tenant_id'), 'drawings', ['tenant_id'], unique=False)
    op.create_table('drawing_reviews',
    sa.Column('drawing_id', sa.UUID(), nullable=False),
    sa.Column('drawing_version_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_drawing_reviews_reviewer_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'drawing_id'], ['drawings.tenant_id', 'drawings.id'], name='fk_drawing_reviews_drawing', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_drawing_reviews_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drawing_reviews')),
    sa.UniqueConstraint('tenant_id', 'drawing_version_id', name='uq_drawing_reviews_version')
    )
    op.create_index('ix_drawing_reviews_drawing', 'drawing_reviews', ['tenant_id', 'drawing_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_drawing_reviews_tenant_id'), 'drawing_reviews', ['tenant_id'], unique=False)
    op.create_table('drawing_versions',
    sa.Column('drawing_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source_object_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'drawing_id'], ['drawings.tenant_id', 'drawings.id'], name='fk_drawing_versions_drawing', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'source_object_id'], ['source_objects.tenant_id', 'source_objects.id'], name='fk_drawing_versions_object', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_drawing_versions_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_drawing_versions_uploaded_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drawing_versions')),
    sa.UniqueConstraint('tenant_id', 'drawing_id', 'version', name='uq_drawing_versions_version')
    )
    op.create_index(op.f('ix_drawing_versions_tenant_id'), 'drawing_versions', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drawing_versions_tenant_id'), table_name='drawing_versions')
    op.drop_table('drawing_versions')
    op.drop_index(op.f('ix_drawing_reviews_tenant_id'), table_name='drawing_reviews')
    op.drop_index('ix_drawing_reviews_drawing', table_name='drawing_reviews')
    op.drop_table('drawing_reviews')
    op.drop_index(op.f('ix_drawings_tenant_id'), table_name='drawings')
    op.drop_index('ix_drawings_queue', table_name='drawings')
    op.drop_index('ix_drawings_assignee', table_name='drawings')
    op.drop_table('drawings')
    # ### end Alembic commands ###
