"""claim set decisions

Revision ID: c3bfa3e15c2b
Revises: 0007_policies_drafting
Create Date: 2026-09-11 13:07:23.466312
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c3bfa3e15c2b'
down_revision: str | None = '0007_policies_drafting'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_set_decisions',
    sa.Column('claim_set_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('claim_set_revision', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_claim_set_decisions_reviewer_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'claim_set_id'], ['claim_sets.tenant_id', 'claim_sets.id'], name='fk_claim_set_decisions_set', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'document_id'], ['documents.tenant_id', 'documents.id'], name='fk_claim_set_decisions_document', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_claim_set_decisions_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim_set_decisions')),
    sa.UniqueConstraint('tenant_id', 'claim_set_id', name='uq_claim_set_decisions_set')
    )
    op.create_index('ix_claim_set_decisions_document', 'claim_set_decisions', ['tenant_id', 'document_id', 'decided_at'], unique=False)
    op.create_index(op.f('ix_claim_set_decisions_tenant_id'), 'claim_set_decisions', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claim_set_decisions_tenant_id'), table_name='claim_set_decisions')
    op.drop_index('ix_claim_set_decisions_document', table_name='claim_set_decisions')
    op.drop_table('claim_set_decisions')
    # ### end Alembic commands ###
