import { CeoMatter, OpportunityItem } from "./ceoLifecycleTypes";

export const SEED_MATTERS: CeoMatter[] = [
  {
    id: "mat-081",
    matter_ref: "MAT-2026-081",
    title: "Quantum-Resistant Lattice Key Exchange Protocol",
    stage: "PROTECT",
    lead_inventor: "Dr. Aris Thorne",
    novelty_score: 94,
    est_filing_cost: 14500,
    risk_level: "LOW",
    confidence_score: 95,
    submitted_date: "2026-09-28",
    conclusion: "Complete independent claim tree meets 35 U.S.C. 101/102/103 patentability thresholds with non-provisional filing specifications fully validated.",
    recommendation: "Approve 1-Click statutory USPTO non-provisional filing and authorize fee docket disbursement.",
    next_action: "Submit EFS-Web specification package and disburse official USPTO filing fee.",
    status: "PENDING_REVIEW",
    evidence: [
      {
        id: "ev-1",
        title: "NIST PQC Round 4 Cryptographic Benchmarking",
        category: "TECHNICAL_BENCHMARK",
        description: "Tested across 10,000 asynchronous handshakes; zero key leakage observed with 12ms mean latency on commodity ARM chips.",
        telemetryValue: "11.8ms keygen latency | 256-bit quantum safety",
        confidenceScore: 98,
        verifiedAt: "2026-09-25",
      },
      {
        id: "ev-2",
        title: "Prior Art Collision Matrix Analysis",
        category: "PRIOR_ART",
        description: "Cross-checked against 4.2M USPTO/EPO/WIPO patents. Closest reference US10928371B2 lacks polynomial ring dimension modulus.",
        telemetryValue: "0 fatal collisions | 1 minor overlap resolved",
        confidenceScore: 94,
        verifiedAt: "2026-09-26",
      },
      {
        id: "ev-3",
        title: "Section 101 Patent Eligibility Clearance",
        category: "STATUTORY_CLEARANCE",
        description: "Hardware-tied physical transformation ensures resistance to Alice/Mayo abstract idea rejections under MPEP 2106.",
        telemetryValue: "101 Clearance Verified",
        confidenceScore: 96,
        verifiedAt: "2026-09-27",
      },
    ],
    counterarguments: [
      {
        id: "ca-1",
        examinerQuery: "Potential 103 obviousness rejection against combinations of Kyber and Dilithium schemes.",
        riskSeverity: "MEDIUM",
        rebuttalStrategy: "Claim 1 explicitly specifies asymmetric trapdoor dimensionality not disclosed or suggested in cited references.",
        status: "ADDRESSED",
      },
    ],
    missing_info: [
      {
        id: "mi-1",
        requiredData: "Final inventor oath notarization from secondary contributor.",
        impactedClaim: "All claims",
        urgency: "LOW",
        assignedTo: "Dr. Aris Thorne",
      },
    ],
    decision_history: [],
  },
  {
    id: "mat-094",
    matter_ref: "MAT-2026-094",
    title: "Autonomous Sub-Surface Acoustic Sensor Swarm",
    stage: "PROTECT",
    lead_inventor: "Dr. Elena Rostova",
    novelty_score: 89,
    est_filing_cost: 12200,
    risk_level: "MODERATE",
    confidence_score: 91,
    submitted_date: "2026-09-30",
    conclusion: "Sonar beamforming hardware integration and autonomous ping relay have completed drafting clearance.",
    recommendation: "Approve for immediate USPTO provisional filing with prioritized examination request.",
    next_action: "Authorize track-one expedited fee docket.",
    status: "PENDING_REVIEW",
    evidence: [
      {
        id: "ev-4",
        title: "Subsea Acoustic Hydrophone Coherence",
        category: "REDUCTION_TO_PRACTICE",
        description: "Simulated 300m oceanic testing array maintained 99.4% acoustic packet relay fidelity.",
        telemetryValue: "99.4% packet relay @ 300m depth",
        confidenceScore: 92,
        verifiedAt: "2026-09-29",
      },
    ],
    counterarguments: [
      {
        id: "ca-2",
        examinerQuery: "Existing navy acoustic telemetry patents may encompass broad swarm aggregation.",
        riskSeverity: "HIGH",
        rebuttalStrategy: "Narrowed Claim 1 to distributed phase-locked loop synchronization with dynamic salinity drift compensation.",
        status: "ADDRESSED",
      },
    ],
    missing_info: [],
    decision_history: [],
  },
  {
    id: "mat-102",
    matter_ref: "MAT-2026-102",
    title: "Zero-Knowledge Biometric Identity Attestation",
    stage: "CLAIM",
    lead_inventor: "Dr. Marcus Vance",
    novelty_score: 91,
    est_filing_cost: 11000,
    risk_level: "LOW",
    confidence_score: 88,
    submitted_date: "2026-10-01",
    conclusion: "Independent method and system claims isolate cryptographic zero-knowledge circuit from raw biometric telemetry.",
    recommendation: "Authorize drafting counsel to lock claim tree with dependent claims 2-18.",
    next_action: "Finalize claim tree hierarchy and advance to Protect stage.",
    status: "PENDING_REVIEW",
    evidence: [
      {
        id: "ev-5",
        title: "zk-SNARK Circuit Verification Proofs",
        category: "TECHNICAL_BENCHMARK",
        description: "Prover time reduced to 142ms on mobile client with zero iris hash leakage.",
        telemetryValue: "142ms proof generation",
        confidenceScore: 90,
        verifiedAt: "2026-10-01",
      },
    ],
    counterarguments: [
      {
        id: "ca-3",
        examinerQuery: "Whether raw biometric vector extraction constitutes patent-ineligible mental process.",
        riskSeverity: "MEDIUM",
        rebuttalStrategy: "Emphasize hardware-enclave secure enclave boundary transform.",
        status: "OPEN",
      },
    ],
    missing_info: [
      {
        id: "mi-2",
        requiredData: "Formal dependent claim review from external counsel.",
        impactedClaim: "Claims 8-12",
        urgency: "MEDIUM",
        assignedTo: "David Chen",
      },
    ],
    decision_history: [],
  },
  {
    id: "mat-115",
    matter_ref: "MAT-2026-115",
    title: "Distributed Edge Neuromorphic Signal Accelerator",
    stage: "ARCHITECT",
    lead_inventor: "David Chen",
    novelty_score: 88,
    est_filing_cost: 13800,
    risk_level: "MODERATE",
    confidence_score: 84,
    submitted_date: "2026-10-02",
    conclusion: "Hardware block diagram and asynchronous spiking neural network logic architecture formulated.",
    recommendation: "Commission formal FIG 1-8 technical drawings from Design Team.",
    next_action: "Approve specification architecture and commission patent drawings.",
    status: "PENDING_REVIEW",
    evidence: [
      {
        id: "ev-6",
        title: "Energy Consumption per Synaptic Event",
        category: "TECHNICAL_BENCHMARK",
        description: "Demonstrated 0.4pJ energy efficiency per event, outperforming baseline GPU inference by 48x.",
        telemetryValue: "0.4pJ / event | 48x energy efficiency",
        confidenceScore: 89,
        verifiedAt: "2026-10-02",
      },
    ],
    counterarguments: [],
    missing_info: [],
    decision_history: [],
  },
  {
    id: "mat-128",
    matter_ref: "MAT-2026-128",
    title: "Cryogenic Superconducting Logic Switching Cell",
    stage: "PROVE",
    lead_inventor: "Dr. Jennifer Wu",
    novelty_score: 96,
    est_filing_cost: 16500,
    risk_level: "LOW",
    confidence_score: 94,
    submitted_date: "2026-10-03",
    conclusion: "Laboratory bench tests demonstrated 4.2K switching speeds under 0.8 picoseconds with 99.98% coherence.",
    recommendation: "Lock reduction-to-practice evidentiary log and initiate formal architecture blueprint.",
    next_action: "Advance to Architect stage.",
    status: "PENDING_REVIEW",
    evidence: [
      {
        id: "ev-7",
        title: "Cryogenic Testbench Coherence Metric",
        category: "REDUCTION_TO_PRACTICE",
        description: "Continuous 72-hour Josephson junction pulse test verified zero flux quantum jump errors.",
        telemetryValue: "0 flux quantum slip errors / 72h",
        confidenceScore: 97,
        verifiedAt: "2026-10-03",
      },
    ],
    counterarguments: [],
    missing_info: [],
    decision_history: [],
  },
  {
    id: "mat-140",
    matter_ref: "MAT-2026-140",
    title: "Dynamic Beamforming Polarization Array for LEO Satellites",
    stage: "CAPTURE",
    lead_inventor: "Samuel K. Okon",
    novelty_score: 85,
    est_filing_cost: 10500,
    risk_level: "HIGH",
    confidence_score: 78,
    submitted_date: "2026-10-04",
    conclusion: "Novel phased-array antenna topology submitted via invention disclosure.",
    recommendation: "Conduct deeper prior art landscape sweep across IEEE and WIPO databases.",
    next_action: "Run automated AI prior art search.",
    status: "PENDING_REVIEW",
    evidence: [
      {
        id: "ev-8",
        title: "Initial RF Simulation Antenna Gain",
        category: "TECHNICAL_BENCHMARK",
        description: "Simulated beamforming gain exceeds 28 dBi at 14 GHz Ku-band with 32 element array.",
        telemetryValue: "28.4 dBi gain @ 14 GHz",
        confidenceScore: 82,
        verifiedAt: "2026-10-04",
      },
    ],
    counterarguments: [],
    missing_info: [
      {
        id: "mi-3",
        requiredData: "Sub-band Doppler shift telemetry in non-geostationary orbit.",
        impactedClaim: "Invention Scope",
        urgency: "CRITICAL",
        assignedTo: "Samuel K. Okon",
      },
    ],
    decision_history: [],
  },
  {
    id: "mat-065",
    matter_ref: "MAT-2026-065",
    title: "Photonic Tensor Core for Real-Time Inference",
    stage: "COMPOUND",
    lead_inventor: "Dr. Aris Thorne",
    novelty_score: 92,
    est_filing_cost: 15000,
    risk_level: "LOW",
    confidence_score: 97,
    submitted_date: "2026-08-15",
    conclusion: "Base patent granted (US Patent #11,842,109). Derivative white-space identified in silicon-interposer wafer packaging.",
    recommendation: "File continuation-in-part (CIP) disclosure and spawn spin-off commercial licensing opportunity.",
    next_action: "Spawn 3 new invention disclosures in White-Space pipeline.",
    status: "FILED",
    evidence: [
      {
        id: "ev-9",
        title: "Granted US Patent #11,842,109 Certificate",
        category: "STATUTORY_CLEARANCE",
        description: "Official USPTO issue notification received and defensive moat active.",
        telemetryValue: "US Pat #11,842,109 Issued",
        confidenceScore: 100,
        verifiedAt: "2026-08-15",
      },
    ],
    counterarguments: [],
    missing_info: [],
    decision_history: [],
  },
];

export const SEED_OPPORTUNITIES: OpportunityItem[] = [
  {
    id: "opp-1",
    title: "Silicon Interposer 3D Optical Bus Continuation (CIP)",
    category: "DERIVATIVE_CIP",
    originMatterRef: "MAT-2026-065",
    marketValueEst: "8.4M",
    defensibilityScore: 94,
    whyRationale: "Directly extends granted photonic tensor claims to 3D stacked die configurations, creating an exclusionary perimeter against emerging AI chip competitors.",
    spinoffIdea: "Three-Dimensional Monolithic Optical Tensor Interconnect Architecture",
    priority: "HIGH",
  },
  {
    id: "opp-2",
    title: "Quantum Key Distribution for Terrestrial 6G Fronthaul",
    category: "WHITE_SPACE",
    originMatterRef: "MAT-2026-081",
    marketValueEst: "4.2M",
    defensibilityScore: 91,
    whyRationale: "WIPO patent radar reveals an unpatented whitespace in lattice key derivation for cellular baseband switches.",
    spinoffIdea: "Low-Latency Post-Quantum Handshake in 6G Radio Access Networks",
    priority: "STRATEGIC",
  },
  {
    id: "opp-3",
    title: "Sub-Surface Environmental Seismic Monitor Spin-Off",
    category: "CROSS_LICENSING",
    originMatterRef: "MAT-2026-094",
    marketValueEst: "2.5M",
    defensibilityScore: 88,
    whyRationale: "Acoustic swarm algorithms have high licensing utility in offshore geothermal and renewable ocean energy infrastructure.",
    spinoffIdea: "Geothermal Fracture Acoustic Resonance Detector Swarm",
    priority: "MEDIUM",
  },
];

export function getInitialMatters(): CeoMatter[] {
  return [];
}

export function saveMatters(matters: CeoMatter[]) {
  if (typeof window === "undefined") return;
  try {
    localStorage.setItem("moat_ceo_lifecycle_matters", JSON.stringify(matters));
    
    // Also synchronize moat_ceo_approvals for backward compatibility with 1-Click Filing table
    const approvals = matters
      .filter((m) => m.stage === "PROTECT")
      .map((m) => ({
        id: m.id,
        matter_ref: m.matter_ref,
        title: m.title,
        lead_inventor: m.lead_inventor,
        novelty_score: m.novelty_score,
        est_filing_cost: m.est_filing_cost,
        risk_level: m.risk_level,
        submitted_date: m.submitted_date,
      }));
    localStorage.setItem("moat_ceo_approvals", JSON.stringify(approvals));
  } catch (e) {
    console.error("Error saving matters to localStorage", e);
  }
}
